#-------------DYNAMODB-------------------------------
pokemonsTableName: Pokemons
pokemonsSeeder: [./seeds/pokemons.json]

#-------------SNS------------------------------------
getPokemonByIdTopicName: getPokemonByIdTopic
getPokemonByNameTopicName: getPokemonByNameTopic

#-------------API GATEWAY---------------------------
apiUrls:
  pokemons: pokemons

#----------AccountId----------
accountIdNumber: 533796783460

